easy_admin:
    design:
        menu:
          - label: 'Particulier'
            icon: 'user'
            children:
              - {entity: 'Parent'}
              - {entity: 'Enfant'}
              - {entity: 'Allergie'}
              - {entity: 'Maladie'}
              - {entity: 'Equipement'}

          - label: 'Structure'
            children:
              - {entity: 'Structure'}
              - {entity: 'AuthorizeUser'}
          - label: 'Pivot Enfant / structure'
            children:
              - {entity: 'Pivot'}

    entities:
      Parent:
        class: App\Entity\Parents
      Enfant:
        class: App\Entity\Child
      Structure:
        class: App\Entity\Structure
      AuthorizeUser:
        class: App\Entity\AuthorizeUser
      Allergie:
        class: App\Entity\Allergy
      Maladie:
        class: App\Entity\Disease
      Equipement:
        class: App\Entity\Equipment
      Pivot:
        class: App\Entity\PivotChildStructure

#  # List the entity class name you want to manage
#  - App\Entity\PivotProchild
