security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers.

    #        chain_provider:
    #            chain:
    #                providers: [parents, structure]
    #        structure:
    #            entity: { class: App\Entity\Structure, property: structure_mail}
    ##        users:
    ##            entity:
    ##                class: 'App\Entity\Parents'
    ##                property: 'parents_mail'
    encoders:
        App\Entity\Structure:
            algorithm: bcrypt
            cost: 13
        App\Entity\Parents:
            algorithm: bcrypt
            cost: 13
    providers:
        parents:
            entity: { class: App\Entity\Parents, property: parents_mail}
        structures:
            entity: { class: App\Entity\Structure, property: structure_mail}

    firewalls:
#        dev:
#            pattern: ^/(_(profiler|wdt)|css|images|js)/
#            security: false
        parents:
            pattern: /login_parents
            anonymous: true
            provider: parents
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            logout:
                path: /logout
                target: /
        structures:
            pattern: /login_structure
            provider: structures
            guard:
                authenticators:
                    - App\Security\LoginFromStructureAuthenticator
                entry_point: App\Security\LoginFromStructureAuthenticator
            form_login:
                login_path: /login_structure
                check_path: /login_structure
            logout:
                path: /logout
                target: /


            # activate different ways to authenticate

            # http_basic: true
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: true
            # https://symfony.com/doc/current/security/form_login_setup.html

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
