easy_admin:
  entities:
    Allergy:
      class: App\Entity\Allergy
      list:
        fields:
        - {property: 'id', label: 'ID Allergy', type: 'integer'}
        - {property: 'severity_id_child', label: 'Nom enfant', type: 'string'}
        - {property: 'allergy_name', label: 'Nom allergie', type: 'string'}
        - {property: 'allergy_therapy', label: 'Traitement', type: 'string'}
        - {property: 'allergy_severity', label: 'Severité', type: 'string'}
        - {property: 'equipment_created_at', label: 'Créer le', type: 'datetime'}
        - {property: 'equipment_updated_at', label: 'Dernière modification', type: 'datetime'}