easy_admin:
  entities:
    Equipment:
      class: App\Entity\Equipment
      list:
        fields:
        - {property: 'id', label: 'ID Equipement', type: 'integer'}
        - {property: 'equipment_id_child', label: 'Nom enfant', type: 'string'}
        - {property: 'equipment_name', label: 'Nom équipement', type: 'string'}
        - {property: 'equipment_created_at', label: 'Créer le', type: 'datetime'}
        - {property: 'equipment_updated_at', label: 'Dernière modification', type: 'datetime'}