easy_admin:
  entities:
    PivotChildStructure:
      class: App\Entity\PivotChildStructure
      list:
        fields:
        - {property: 'id', label: 'ID Pivot', type: 'integer'}
        - {property: 'Pivot_id_child', label: 'ID Enfant', type: 'string'}
        - {property: 'Pivot_id_structure', label: 'ID Structure', type: 'array'}